// Minecraft 服务器审核系统 - Cloudflare Workers
const QUESTIONS = [
  {"question":"钻石矿石需要什么镐挖掘？","options":["木镐","石镐","铁镐","钻石镐"],"answer":2},
  {"question":"下界传送门用什么建造？","options":["黑曜石","基岩","下界砖","岩浆块"],"answer":0},
  {"question":"末影龙在哪个维度？","options":["主世界","下界","末地","虚空"],"answer":2},
  {"question":"烈焰棒从哪种怪物掉落？","options":["末影人","烈焰人","凋灵骷髅","恶魂"],"answer":1},
  {"question":"末影珍珠从哪种怪物掉落？","options":["末影人","末影龙","潜影贝","末影螨"],"answer":0},
  {"question":"一组物品最多堆叠多少个？","options":["16个","32个","64个","128个"],"answer":2},
  {"question":"铁傀儡会保护哪种生物？","options":["猪","村民","羊","牛"],"answer":1},
  {"question":"苦力怕爆炸后掉落什么？","options":["火药","煤炭","红石","无"],"answer":0},
  {"question":"蜘蛛在白天会怎样？","options":["攻击玩家","中立","逃跑","消失"],"answer":1},
  {"question":"僵尸在阳光下会怎样？","options":["变强","燃烧","消失","无变化"],"answer":1},
  {"question":"骷髅使用什么武器？","options":["剑","弓","斧头","三叉戟"],"answer":1},
  {"question":"恶魂在哪里生成？","options":["主世界","下界","末地","所有维度"],"answer":1},
  {"question":"凋灵需要几个骷髅头召唤？","options":["1个","2个","3个","4个"],"answer":2},
  {"question":"信标基座用什么方块？","options":["石头","铁/金/钻石/绿宝石块","木头","沙子"],"answer":1},
  {"question":"附魔台周围放什么提高等级？","options":["书架","工作台","箱子","熔炉"],"answer":0},
  {"question":"酿造台用什么制作？","options":["圆石+烈焰棒","铁锭+烈焰棒","钻石+烈焰棒","黑曜石+烈焰棒"],"answer":0},
  {"question":"末影箱有什么功能？","options":["容量大","跨维度共享","自动整理","防火"],"answer":1},
  {"question":"铁砧可以做什么？","options":["修复物品","修复和重命名","重命名","合成"],"answer":1},
  {"question":"红石信号最远传输多少格？","options":["8格","15格","16格","32格"],"answer":1},
  {"question":"活塞可以推动多少个方块？","options":["8个","12个","16个","无限"],"answer":1},
  {"question":"水在主世界流动多少格？","options":["4格","7格","8格","无限"],"answer":2},
  {"question":"床在下界会怎样？","options":["睡觉","爆炸","装饰","无法放置"],"answer":1},
  {"question":"玩家默认有多少颗心？","options":["5颗","10颗","15颗","20颗"],"answer":1},
  {"question":"饥饿值有多少格？","options":["5格","10格","15格","20格"],"answer":1},
  {"question":"玩家在水中呼吸多久？","options":["10秒","15秒","20秒","30秒"],"answer":1},
  {"question":"玩家可以跳多高？","options":["0.5格","1格","1.5格","2格"],"answer":1},
  {"question":"疾跑消耗什么？","options":["生命值","饥饿值","经验值","氧气"],"answer":1},
  {"question":"潜行时会发生什么？","options":["移动更快","不掉落方块边缘","隐身","无敌"],"answer":1},
  {"question":"三叉戟从哪种怪物掉落？","options":["溺尸","守卫者","远古守卫者","海豚"],"answer":0},
  {"question":"猫可以吓跑什么怪物？","options":["僵尸","骷髅","苦力怕","蜘蛛"],"answer":2},
  {"question":"狼驯服后用什么繁殖？","options":["骨头","腐肉","任何肉类","小麦"],"answer":2},
  {"question":"幻翼在什么条件下生成？","options":["3天没睡","夜晚","雷暴","下界"],"answer":0},
  {"question":"村民可以交易什么？","options":["食物","工具","附魔书","以上全部"],"answer":3},
  {"question":"工作台有几个合成格子？","options":["4个","6个","9个","12个"],"answer":2},
  {"question":"末影人怕什么？","options":["水","火","岩浆","阳光"],"answer":0},
  {"question":"末影龙有多少颗心？","options":["100颗","200颗","300颗","500颗"],"answer":1},
  {"question":"监守者在哪里生成？","options":["深暗之域","要塞","地牢","废弃矿井"],"answer":0},
  {"question":"古城在哪里生成？","options":["深暗之域","要塞","地牢","废弃矿井"],"answer":0},
  {"question":"要塞有多少个？","options":["1个","3个","128个","无限"],"answer":2},
  {"question":"末地传送门需要多少个末影之眼？","options":["8个","10个","12个","16个"],"answer":2},
  {"question":"烈焰人刷怪笼在哪里？","options":["下界要塞","堡垒遗迹","废弃传送门","任何下界地方"],"answer":0},
  {"question":"僵尸刷怪笼在哪里？","options":["地牢","废弃矿井","要塞","以上全部"],"answer":0},
  {"question":"洞穴蜘蛛刷怪笼在哪里？","options":["地牢","废弃矿井","要塞","以上全部"],"answer":1},
  {"question":"蠹虫刷怪笼在哪里？","options":["地牢","废弃矿井","要塞","以上全部"],"answer":2},
  {"question":"下界有多少种生物群系？","options":["3种","4种","5种","6种"],"answer":2},
  {"question":"废弃传送门在哪里生成？","options":["主世界","下界","主世界和下界","末地"],"answer":2},
  {"question":"林地府邸在哪里生成？","options":["黑森林","深色橡木林","针叶林","丛林"],"answer":0},
  {"question":"沙漠神殿在哪里生成？","options":["沙漠","恶地","热带草原","平顶山"],"answer":0},
  {"question":"丛林神庙在哪里生成？","options":["丛林","竹林","热带雨林","沼泽"],"answer":0},
  {"question":"沼泽小屋在哪里生成？","options":["沼泽","红树林沼泽","河流","海滩"],"answer":0},
  {"question":"制作工作台需要多少木板？","options":["2个","4个","6个","8个"],"answer":1},
  {"question":"制作熔炉需要多少圆石？","options":["6个","8个","9个","10个"],"answer":1},
  {"question":"制作铁桶需要多少铁锭？","options":["2个","3个","4个","5个"],"answer":1},
  {"question":"制作铁剑需要什么？","options":["1铁+1木棍","2铁+1木棍","3铁+1木棍","2铁+2木棍"],"answer":1},
  {"question":"制作钻石镐需要什么？","options":["2钻石+1木棍","3钻石+1木棍","3钻石+2木棍","2钻石+2木棍"],"answer":1},
  {"question":"制作弓需要什么？","options":["2木棍+1线","3木棍+2线","3木棍+3线","2木棍+3线"],"answer":2},
  {"question":"制作箭需要什么？","options":["木棍+燧石","木棍+羽毛","木棍+燧石+羽毛","木棍+铁锭"],"answer":2},
  {"question":"制作火把需要什么？","options":["木棍+煤炭","木棍+木炭","木棍+煤炭或木炭","木棍+红石"],"answer":2},
  {"question":"制作床需要什么？","options":["3木板+2羊毛","3木板+3羊毛","2木板+3羊毛","3木板+1羊毛"],"answer":1},
  {"question":"制作箱子需要多少木板？","options":["6个","8个","9个","10个"],"answer":1},
  {"question":"制作漏斗需要什么？","options":["铁锭+箱子","铁锭+木板","铁锭+圆石","铁锭+漏斗"],"answer":0},
  {"question":"制作活塞需要什么？","options":["木板+圆石+铁锭+红石","木板+圆石+铁锭","木板+圆石+红石","铁锭+红石"],"answer":0},
  {"question":"制作发射器需要什么？","options":["圆石+弓+红石","圆石+弓","圆石+红石","弓+红石"],"answer":0},
  {"question":"制作TNT需要什么？","options":["火药+沙子","火药+红石","火药+沙子或红沙","火药+圆石"],"answer":2},
  {"question":"制作玻璃需要什么？","options":["沙子+熔炉","沙子烧炼","沙子+木棍","沙子+水"],"answer":1},
  {"question":"制作纸需要什么？","options":["3个甘蔗","2个甘蔗","3个小麦","3个竹子"],"answer":0},
  {"question":"制作书需要什么？","options":["3纸+1皮革","3纸","2纸+1皮革","4纸"],"answer":0},
  {"question":"制作书架需要什么？","options":["6木板+3书","6木板+6书","8木板+3书","6木板+2书"],"answer":0},
  {"question":"制作铁块需要多少铁锭？","options":["6个","8个","9个","10个"],"answer":2},
  {"question":"制作金块需要多少金锭？","options":["6个","8个","9个","10个"],"answer":2},
  {"question":"制作钻石块需要多少钻石？","options":["6个","8个","9个","10个"],"answer":2},
  {"question":"制作铁门需要多少铁锭？","options":["4个","5个","6个","8个"],"answer":2},
  {"question":"制作铁栏杆需要多少铁锭？","options":["4个","5个","6个","8个"],"answer":2},
  {"question":"制作干草块需要多少小麦？","options":["6个","8个","9个","10个"],"answer":2},
  {"question":"制作骨块需要多少骨粉？","options":["6个","8个","9个","10个"],"answer":2},
  {"question":"制作粘液块需要多少粘液球？","options":["6个","8个","9个","10个"],"answer":2},
  {"question":"制作蜂蜜块需要多少蜂蜜瓶？","options":["2个","3个","4个","5个"],"answer":2},
  {"question":"制作雪块需要多少雪球？","options":["2个","3个","4个","5个"],"answer":2},
  {"question":"制作粘土块需要多少粘土球？","options":["2个","3个","4个","5个"],"answer":2},
  {"question":"制作砖块需要多少砖？","options":["2个","3个","4个","5个"],"answer":2},
  {"question":"制作下界砖块需要多少下界砖？","options":["2个","3个","4个","5个"],"answer":2},
  {"question":"制作紫珀块需要什么？","options":["紫珀芽","爆裂紫珀果","紫珀楼梯","紫珀台阶"],"answer":1},
  {"question":"制作石英块需要多少下界石英？","options":["2个","3个","4个","5个"],"answer":2},
  {"question":"制作红砂岩需要什么？","options":["4个红沙","4个沙子","4个红石","4个沙岩"],"answer":0},
  {"question":"制作砂岩需要什么？","options":["4个沙子","4个红沙","4个沙砾","4个圆石"],"answer":0},
  {"question":"制作磨制花岗岩需要什么？","options":["4个花岗岩","4个闪长岩","4个安山岩","4个圆石"],"answer":0},
  {"question":"制作磨制闪长岩需要什么？","options":["4个花岗岩","4个闪长岩","4个安山岩","4个圆石"],"answer":1},
  {"question":"制作磨制安山岩需要什么？","options":["4个花岗岩","4个闪长岩","4个安山岩","4个圆石"],"answer":2},
  {"question":"制作红石块需要多少红石？","options":["6个","8个","9个","10个"],"answer":2},
  {"question":"制作青金石块需要多少青金石？","options":["6个","8个","9个","10个"],"answer":2},
  {"question":"制作煤炭块需要多少煤炭？","options":["6个","8个","9个","10个"],"answer":2},
  {"question":"制作绿宝石块需要多少绿宝石？","options":["6个","8个","9个","10个"],"answer":2},
  {"question":"制作金胡萝卜需要什么？","options":["胡萝卜+8金粒","胡萝卜+金锭","胡萝卜+金块","胡萝卜+金苹果"],"answer":0},
  {"question":"制作金苹果需要什么？","options":["苹果+8金粒","苹果+金锭","苹果+金块","苹果+钻石"],"answer":1},
  {"question":"制作闪烁的西瓜需要什么？","options":["西瓜片+8金粒","西瓜片+金锭","西瓜片+金块","西瓜+金粒"],"answer":0},
  {"question":"制作发酵蛛眼需要什么？","options":["蜘蛛眼+糖+蘑菇","蜘蛛眼+糖","蜘蛛眼+蘑菇","蜘蛛眼+红石"],"answer":0},
  {"question":"制作岩浆膏需要什么？","options":["烈焰粉+粘液球","烈焰粉+岩浆","烈焰棒+粘液球","岩浆+粘液球"],"answer":0},
  {"question":"制作末影之眼需要什么？","options":["末影珍珠+烈焰粉","末影珍珠+烈焰棒","末影珍珠+岩浆膏","末影珍珠+火药"],"answer":0},
  {"question":"制作火焰弹需要什么？","options":["烈焰粉+煤炭","烈焰粉+火药+煤炭","烈焰棒+煤炭","烈焰粉+木炭"],"answer":1},
  {"question":"制作烟花火箭需要什么？","options":["火药+纸","火药+纸+火药球","纸+火药球","火药+木棍"],"answer":1},
  {"question":"药水需要什么材料酿造？","options":["水+玻璃瓶","水+烈焰粉","水+地狱疣","水+红石"],"answer":2},
  {"question":"基础药水是什么？","options":["粗制的药水","平凡的药水","浓稠的药水","尴尬的药水"],"answer":0},
  {"question":"夜视药水需要什么？","options":["金胡萝卜","金苹果","金锭","金块"],"answer":0},
  {"question":"隐身药水需要什么？","options":["发酵蛛眼","蜘蛛眼","糖","火药"],"answer":0},
  {"question":"跳跃提升药水需要什么？","options":["兔子脚","兔子皮","兔子肉","兔子汤"],"answer":0},
  {"question":"火焰抗性药水需要什么？","options":["岩浆膏","烈焰粉","烈焰棒","火药"],"answer":0},
  {"question":"速度药水需要什么？","options":["糖","金胡萝卜","金苹果","金锭"],"answer":0},
  {"question":"力量药水需要什么？","options":["烈焰粉","岩浆膏","火药","红石"],"answer":0},
  {"question":"治疗药水需要什么？","options":["闪烁的西瓜","金苹果","金胡萝卜","金锭"],"answer":0},
  {"question":"伤害药水需要什么？","options":["发酵蛛眼","蜘蛛眼","河豚","毒马铃薯"],"answer":0},
  {"question":"再生药水需要什么？","options":["恶魂之泪","金苹果","金胡萝卜","金锭"],"answer":0},
  {"question":"水下呼吸药水需要什么？","options":["河豚","鱼","墨囊","海磷晶体"],"answer":0},
  {"question":"缓降药水需要什么？","options":["幻翼膜","羽毛","鸡肉","兔子脚"],"answer":0},
  {"question":"虚弱药水需要什么？","options":["发酵蛛眼","蜘蛛眼","糖","火药"],"answer":0},
  {"question":"中毒药水需要什么？","options":["蜘蛛眼","发酵蛛眼","河豚","毒马铃薯"],"answer":0},
  {"question":"红石可以延长药水时间吗？","options":["可以","不可以","只能增强","只能减弱"],"answer":0},
  {"question":"萤石粉可以增强药水吗？","options":["可以","不可以","只能延长","只能减弱"],"answer":0},
  {"question":"火药可以使药水变成喷溅药水吗？","options":["可以","不可以","只能延长","只能增强"],"answer":0},
  {"question":"龙息可以使药水变成滞留药水吗？","options":["可以","不可以","只能延长","只能增强"],"answer":0},
  {"question":"金苹果可以吃什么效果？","options":["生命恢复","吸收","以上全部","无效果"],"answer":2},
  {"question":"附魔金苹果可以吃什么效果？","options":["生命恢复","吸收","以上全部","无效果"],"answer":2},
  {"question":"附魔金苹果需要什么制作？","options":["金苹果+金块","金苹果+金锭","金苹果+钻石","无法制作"],"answer":3},
  {"question":"牛奶有什么用？","options":["饮用","清除效果","以上全部","无用途"],"answer":2},
  {"question":"河豚有什么效果？","options":["中毒","饥饿","反胃","虚弱"],"answer":0},
  {"question":"毒马铃薯有什么效果？","options":["中毒","饥饿","反胃","虚弱"],"answer":0},
  {"question":"生鸡肉有什么风险？","options":["中毒","饥饿","反胃","无风险"],"answer":1},
  {"question":"腐肉有什么风险？","options":["中毒","饥饿","反胃","无风险"],"answer":1},
  {"question":"蜘蛛眼可以吃吗？","options":["可以","不可以","只能酿造","只能喂狼"],"answer":0},
  {"question":"金胡萝卜可以吃吗？","options":["可以","不可以","只能酿造","只能交易"],"answer":0},
  {"question":"金苹果可以吃吗？","options":["可以","不可以","只能酿造","只能交易"],"answer":0},
  {"question":"附魔金苹果可以吃吗？","options":["可以","不可以","只能酿造","只能交易"],"answer":0},
  {"question":"恶魂之泪可以喝吗？","options":["可以","不可以","只能酿造","只能装饰"],"answer":0},
  {"question":"蜂蜜瓶可以喝吗？","options":["可以","不可以","只能酿造","只能装饰"],"answer":0},
  {"question":"蜂蜜瓶有什么效果？","options":["治疗","清除中毒","以上全部","无效果"],"answer":2},
  {"question":"药水可以叠加吗？","options":["可以","不可以","只能1个","只能16个"],"answer":1},
  {"question":"喷溅药水可以叠加吗？","options":["可以","不可以","只能1个","只能16个"],"answer":1},
  {"question":"滞留药水可以叠加吗？","options":["可以","不可以","只能1个","只能16个"],"answer":1},
  {"question":"药水可以在酿造台酿造吗？","options":["可以","不可以","只能工作台","只能熔炉"],"answer":0},
  {"question":"酿造台需要什么燃料？","options":["烈焰粉","煤炭","岩浆","不需要"],"answer":0},
  {"question":"酿造台有多少个槽位？","options":["1个","2个","3个","4个"],"answer":2},
  {"question":"玻璃瓶可以装水吗？","options":["可以","不可以","只能装药水","只能装蜂蜜"],"answer":0},
  {"question":"玻璃瓶可以装蜂蜜吗？","options":["可以","不可以","只能装水","只能装药水"],"answer":0},
  {"question":"玻璃瓶可以装药水吗？","options":["可以","不可以","只能装水","只能装蜂蜜"],"answer":0},
  {"question":"药水可以倒掉吗？","options":["可以","不可以","只能喝掉","只能扔掉"],"answer":0},
  {"question":"喷溅药水可以扔吗？","options":["可以","不可以","只能喝","只能倒"],"answer":0},
  {"question":"滞留药水可以扔吗？","options":["可以","不可以","只能喝","只能倒"],"answer":0},
  {"question":"滞留药水会留下云吗？","options":["会","不会","只在水中","只在岩浆中"],"answer":0},
  {"question":"药水云持续多久？","options":["10秒","20秒","30秒","60秒"],"answer":2},
  {"question":"药水云可以叠加吗？","options":["可以","不可以","只能1个","只能2个"],"answer":1},
  {"question":"药水效果可以叠加吗？","options":["可以","不可以","只能延长","只能增强"],"answer":1},
  {"question":"附魔台需要多少经验？","options":["1-30级","1-50级","1-100级","固定30级"],"answer":0},
  {"question":"铁砧需要多少经验？","options":["1-39级","1-30级","1-50级","无限"],"answer":0},
  {"question":"铁砧会损坏吗？","options":["会","不会","只能修复","只能重命名"],"answer":0},
  {"question":"铁砧可以合并附魔吗？","options":["可以","不可以","只能修复","只能重命名"],"answer":0},
  {"question":"附魔书需要什么制作？","options":["书+附魔台","书+铁砧","书+青金石","书+经验"],"answer":0},
  {"question":"锋利附魔有什么用？","options":["增加伤害","增加击退","增加攻速","增加耐久"],"answer":0},
  {"question":"保护附魔有什么用？","options":["减少伤害","增加护甲","增加生命","增加速度"],"answer":0},
  {"question":"效率附魔有什么用？","options":["加快挖掘速度","增加耐久","增加掉落","增加伤害"],"answer":0},
  {"question":"耐久附魔有什么用？","options":["增加耐久度","增加伤害","增加速度","增加护甲"],"answer":0},
  {"question":"时运附魔有什么用？","options":["增加掉落","增加耐久","增加速度","增加伤害"],"answer":0},
  {"question":"精准采集附魔有什么用？","options":["采集方块本身","增加掉落","增加耐久","增加速度"],"answer":0},
  {"question":"火焰附加附魔有什么用？","options":["点燃目标","增加伤害","增加击退","增加攻速"],"answer":0},
  {"question":"击退附魔有什么用？","options":["击退目标","增加伤害","点燃目标","增加攻速"],"answer":0},
  {"question":"抢夺附魔有什么用？","options":["增加掉落","增加伤害","增加击退","增加攻速"],"answer":0},
  {"question":"无限附魔有什么用？","options":["箭矢无限","耐久无限","伤害无限","速度无限"],"answer":0},
  {"question":"力量附魔有什么用？","options":["增加弓箭伤害","增加弓箭速度","增加弓箭距离","增加弓箭耐久"],"answer":0},
  {"question":"冲击附魔有什么用？","options":["增加弓箭击退","增加弓箭伤害","增加弓箭速度","增加弓箭距离"],"answer":0},
  {"question":"火矢附魔有什么用？","options":["点燃目标","增加伤害","增加击退","增加速度"],"answer":0},
  {"question":"水下速掘附魔有什么用？","options":["水下挖掘不减速","水下呼吸","水下夜视","水下防火"],"answer":0},
  {"question":"深海探索者附魔有什么用？","options":["水下行走更快","水下挖掘更快","水下呼吸","水下夜视"],"answer":0},
  {"question":"冰霜行者附魔有什么用？","options":["水上行走","水下呼吸","水下挖掘","水下夜视"],"answer":0},
  {"question":"经验修补附魔有什么用？","options":["用经验修复物品","用物品修复物品","自动修复","无效果"],"answer":0},
  {"question":"绑定诅咒附魔有什么用？","options":["无法取下装备","装备自动穿上","装备无法损坏","无效果"],"answer":0},
  {"question":"消失诅咒附魔有什么用？","options":["死亡后物品消失","物品无法取下","物品无法损坏","无效果"],"answer":0},
  {"question":"穿刺附魔有什么用？","options":["增加对水生生物伤害","增加对所有生物伤害","增加击退","增加攻速"],"answer":0},
  {"question":"激流附魔有什么用？","options":["雨天可飞行","增加伤害","增加击退","增加攻速"],"answer":0},
  {"question":"忠诚附魔有什么用？","options":["三叉戟返回","增加伤害","增加击退","增加攻速"],"answer":0},
  {"question":"引雷附魔有什么用？","options":["雷暴时召唤闪电","增加伤害","增加击退","增加攻速"],"answer":0},
  {"question":"横扫之刃附魔有什么用？","options":["横扫攻击","增加伤害","增加击退","增加攻速"],"answer":0},
  {"question":"多重射击附魔有什么用？","options":["射出多支箭","增加伤害","增加击退","增加攻速"],"answer":0},
  {"question":"快速装填附魔有什么用？","options":["加快装填速度","增加伤害","增加击退","增加攻速"],"answer":0},
  {"question":"穿透附魔有什么用？","options":["穿透敌人","增加伤害","增加击退","增加攻速"],"answer":0},
  {"question":"附魔台周围最多放多少书架？","options":["10个","15个","20个","30个"],"answer":1},
  {"question":"附魔台最高等级是多少？","options":["20级","30级","40级","50级"],"answer":1},
  {"question":"青金石有什么用？","options":["附魔","染色","以上全部","无用途"],"answer":2},
  {"question":"附魔需要青金石吗？","options":["需要","不需要","可选","只有高级附魔需要"],"answer":0},
  {"question":"附魔需要经验吗？","options":["需要","不需要","可选","只有高级附魔需要"],"answer":0},
  {"question":"铁砧修复需要经验吗？","options":["需要","不需要","可选","只有高级修复需要"],"answer":0},
  {"question":"铁砧重命名需要经验吗？","options":["需要","不需要","可选","只有长名字需要"],"answer":0},
  {"question":"铁砧合并附魔需要经验吗？","options":["需要","不需要","可选","只有高级附魔需要"],"answer":0},
  {"question":"附魔书可以在铁砧使用吗？","options":["可以","不可以","只能在附魔台","只能在工作台"],"answer":0},
  {"question":"附魔书可以在附魔台使用吗？","options":["可以","不可以","只能在铁砧","只能在工作台"],"answer":0},
  {"question":"附魔书可以合并吗？","options":["可以","不可以","只能在附魔台","只能在工作台"],"answer":0},
  {"question":"附魔书可以叠加吗？","options":["可以","不可以","只能1个","只能16个"],"answer":0},
  {"question":"锋利附魔最高几级？","options":["3级","4级","5级","6级"],"answer":2},
  {"question":"保护附魔最高几级？","options":["3级","4级","5级","6级"],"answer":1},
  {"question":"效率附魔最高几级？","options":["3级","4级","5级","6级"],"answer":2},
  {"question":"耐久附魔最高几级？","options":["1级","2级","3级","4级"],"answer":2},
  {"question":"时运附魔最高几级？","options":["1级","2级","3级","4级"],"answer":2},
  {"question":"击退附魔最高几级？","options":["1级","2级","3级","4级"],"answer":1}
];

const DEFAULT_CONFIG = {
  titles: ["Minecraft 服务器审核", "欢迎来到服务器", "证明你的实力"],
  password: "审核通过",
  quiz: { count: 50, passRate: 80, timeLimit: 600 },
  style: {
    background: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1920",
    primaryColor: "#00ff88"
  }
};

function esc(s) { return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); }

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function generateHTML(c) {
  return `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${esc(c.titles[0])}</title><link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet"><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:"Press Start 2P",monospace;min-height:100vh;display:flex;align-items:center;justify-content:center;background:url("${c.style.background}") center/cover fixed;color:#fff;padding:20px}body::before{content:"";position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,0.7);z-index:-1}.container{background:rgba(0,0,0,0.85);border-radius:16px;padding:40px;max-width:800px;width:100%;box-shadow:0 0 30px ${c.style.primaryColor}40;border:2px solid ${c.style.primaryColor}}.title{text-align:center;margin-bottom:30px;font-size:14px;color:${c.style.primaryColor};text-shadow:0 0 10px ${c.style.primaryColor}}.typewriter{overflow:hidden;border-right:3px solid ${c.style.primaryColor};white-space:nowrap;animation:typing 2s steps(30,end),blink-caret .75s step-end infinite;display:inline-block}@keyframes typing{from{width:0}to{width:100%}}@keyframes blink-caret{from,to{border-color:transparent}50%{border-color:${c.style.primaryColor}}}.btn{width:100%;padding:15px;border:none;border-radius:8px;background:linear-gradient(135deg,${c.style.primaryColor},${c.style.primaryColor}aa);color:#1a1a2e;font-family:inherit;font-size:12px;cursor:pointer;transition:all .3s;margin-top:20px}.btn:hover{transform:translateY(-2px)}.btn:disabled{background:#333;color:#666;cursor:not-allowed}.hidden{display:none}.info-box{margin-top:30px;font-size:8px;color:#888;line-height:2}.progress-bar{background:#333;border-radius:10px;height:20px;margin-bottom:20px}.progress-fill{background:${c.style.primaryColor};height:100%;transition:width .3s;display:flex;align-items:center;justify-content:center;font-size:8px;color:#1a1a2e}.timer{text-align:center;font-size:20px;color:#ff6b6b;margin-bottom:20px}.timer.warning{animation:pulse .5s infinite}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}.question-box{background:rgba(255,255,255,.05);border-radius:12px;padding:20px;margin-bottom:20px}.question-num{font-size:10px;color:#888;margin-bottom:10px}.question-text{font-size:12px;line-height:1.8;margin-bottom:20px}.options{display:flex;flex-direction:column;gap:10px}.option{background:rgba(255,255,255,.1);border:2px solid #333;border-radius:8px;padding:15px;cursor:pointer;transition:all .2s;font-size:10px}.option:hover{border-color:${c.style.primaryColor}}.option.selected{border-color:${c.style.primaryColor};background:rgba(0,255,136,.2)}.result-box{text-align:center;padding:40px}.score{font-size:48px;color:${c.style.primaryColor};margin:20px 0}.score.failed{color:#ff6b6b}.password-display{font-size:18px;text-align:center;padding:20px;background:rgba(0,255,136,.1);border-radius:8px;margin:20px 0;letter-spacing:3px;color:${c.style.primaryColor}}.stats{font-size:10px;color:#888;margin-top:20px;line-height:2}</style></head><body><div class="container"><div id="startPage"><h1 class="title"><span class="typewriter" id="titleText">${esc(c.titles[0])}</span></h1><button class="btn" onclick="startQuiz()">开始答题</button><div class="info-box"><p>共 ${c.quiz.count} 道单选题</p><p>题库: 200 道随机抽取</p><p>时间限制: ${Math.floor(c.quiz.timeLimit/60)} 分钟</p><p>通过分数: ${c.quiz.passRate}%</p></div></div><div id="quizPage" class="hidden"><h1 class="title">${esc(c.titles[0])}</h1><div class="timer" id="timer">${Math.floor(c.quiz.timeLimit/60)}:00</div><div class="progress-bar"><div class="progress-fill" id="progress" style="width:0%">0/${c.quiz.count}</div></div><div class="question-box"><div class="question-num" id="questionNum">第 1 题 / 共 ${c.quiz.count} 题</div><div class="question-text" id="questionText">加载中...</div><div class="options" id="options"></div></div><button class="btn" id="nextBtn" onclick="nextQuestion()" disabled>下一题</button></div><div id="resultPage" class="hidden"><div class="result-box"><h1 class="title">答题结果</h1><div class="score" id="score">0%</div><p id="resultText" style="font-size:10px;margin-bottom:20px"></p><div id="passwordBox" class="hidden"><p style="font-size:10px;margin-bottom:10px">验证密码：</p><div class="password-display" id="password"></div></div><div class="stats" id="stats"></div><button class="btn" onclick="location.reload()">重新答题</button></div></div></div><script>var CONFIG=${JSON.stringify(c)};var TITLES=${JSON.stringify(c.titles)};var titleIdx=0,Q=[],cur=0,corr=0,sel=null,TL=${c.quiz.timeLimit},tmr=null,startTime=null,endTime=null;setInterval(function(){titleIdx=(titleIdx+1)%TITLES.length;document.getElementById("titleText").textContent=TITLES[titleIdx]},3000);function startQuiz(){startTime=new Date();document.getElementById("startPage").classList.add("hidden");document.getElementById("quizPage").classList.remove("hidden");fetch("/api/quiz/start").then(r=>r.json()).then(d=>{Q=d.questions;showQuestion();startTimer()}).catch(e=>{alert("网络错误");location.reload()})}function showQuestion(){var q=Q[cur];document.getElementById("questionNum").textContent="第 "+(cur+1)+" 题 / 共 "+Q.length+" 题";document.getElementById("questionText").textContent=q.question;var opts=document.getElementById("options");opts.innerHTML="";q.options.forEach(function(o,i){var div=document.createElement("div");div.className="option";div.textContent=String.fromCharCode(65+i)+". "+o;div.onclick=function(){selectOption(i)};opts.appendChild(div)});document.getElementById("progress").style.width=(cur/Q.length*100)+"%";document.getElementById("progress").textContent=cur+"/"+Q.length;document.getElementById("nextBtn").disabled=true;sel=null}function selectOption(idx){sel=idx;document.querySelectorAll(".option").forEach(function(el,i){el.classList.toggle("selected",i===idx)});document.getElementById("nextBtn").disabled=false}function nextQuestion(){if(sel===null)return;if(sel===Q[cur].answer)corr++;cur++;if(cur>=Q.length){endQuiz();return}showQuestion()}function startTimer(){tmr=setInterval(function(){TL--;var m=Math.floor(TL/60),s=TL%60;document.getElementById("timer").textContent=m+":"+(s<10?"0":"")+s;if(TL<=60)document.getElementById("timer").classList.add("warning");if(TL<=0){clearInterval(tmr);endQuiz()}},1000)}function formatTime(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")+" "+String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0")+":"+String(d.getSeconds()).padStart(2,"0")}function endQuiz(){clearInterval(tmr);endTime=new Date();document.getElementById("quizPage").classList.add("hidden");document.getElementById("resultPage").classList.remove("hidden");var score=Math.round(corr/Q.length*100);var passed=corr>=Math.ceil(Q.length*CONFIG.quiz.passRate/100);document.getElementById("score").textContent=score+"%";document.getElementById("score").classList.toggle("failed",!passed);document.getElementById("resultText").textContent=passed?"恭喜通过！答对 "+corr+"/"+Q.length+" 题":"未通过，答对 "+corr+"/"+Q.length+" 题";if(passed){document.getElementById("passwordBox").classList.remove("hidden");document.getElementById("password").textContent=CONFIG.password}var duration=Math.floor((endTime-startTime)/1000);var min=Math.floor(duration/60),sec=duration%60;document.getElementById("stats").innerHTML="开始时间: "+formatTime(startTime)+"<br>结束时间: "+formatTime(endTime)+"<br>用时: "+min+"分"+sec+"秒<br>正确率: "+score+"%"}</script></body></html>`;
}

export default {
  async fetch(req, env) {
    const url = new URL(req.url);
    const config = env.CONFIG ? JSON.parse(env.CONFIG) : DEFAULT_CONFIG;
    
    if (url.pathname === "/" || url.pathname === "/index.html") {
      return new Response(generateHTML(config), { headers: { "Content-Type": "text/html; charset=utf-8" }});
    }
    
    if (url.pathname === "/api/quiz/start") {
      const shuffled = shuffle(QUESTIONS);
      const selected = shuffled.slice(0, config.quiz.count);
      return Response.json({ questions: selected });
    }
    
    return new Response("Not Found", { status: 404 });
  }
};
